name: Auto update sqlite jdbc

on:
  schedule:
    # runs Tue at 12:00 am
    - cron: '0 0 * * 2'
  push:
  workflow_dispatch:
    inputs:
      version:
        description: dummy
        default: dummy


jobs:
  auto-update-dependencies:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Run auto dependency check
      run: ./tools/check_sqlite_jdbc.sh nocommit

    - name: check for changes
      run:  git diff || echo "no changes"

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v7
      with:
        commit-message: update sqlite jdbc
        branch: create-pull-request/sqlite_jdbc
        delete-branch: true
        title: 'update sqlite jdbc'

