workflows:
  JNI Libs macOS silicone:
    name: build-macos-jni-artifact
    instance_type: mac_mini_m1
    environment:
      java: 17
#    triggering:
#      events:
#        - push
#        - pull_request
    scripts:
        - brew install git automake yasm nasm

        - |
          ls -al
          id
          pwd
          ./circle_scripts/deps_macos.sh

        - |
          ls -al
          id
          pwd
          ./circle_scripts/java_jni_lib_macos.sh

        - pwd
        - find . -name 'libjni-c-toxcore.jnilib'
        - ls -al /Users/runner/ToxAndroidRefImpl/jni-c-toxcore/libjni-c-toxcore.jnilib
        - mv -v /Users/runner/ToxAndroidRefImpl/jni-c-toxcore/libjni-c-toxcore.jnilib /Users/runner/ToxAndroidRefImpl/jni-c-toxcore/libjni-c-toxcore_arm64.jnilib

    artifacts:
      - /Users/runner/ToxAndroidRefImpl/jni-c-toxcore/libjni-c-toxcore_arm64.jnilib

  test macOS silicone:
    name: macos-test
    instance_type: mac_mini_m1
    environment:
      java: 17
#    triggering:
#      events:
#        - push
#        - pull_request
    scripts:
        - brew install cliclick wget
        - brew install socsieng/tap/sendkeys
        - sw_vers -productVersion
        - |
          curl -L https://github.com/zoff99/java_tox_tester/archive/refs/heads/master.zip -o master.zip
          unzip master.zip
          pwd
          ls -al /Users/builder/clone/java_tox_tester-master/
          java -version
          javac -version

        - |
          pwd
          mkdir -p /Users/builder/clone/
          ls -al /Users/builder/clone/
          _HOME_="/Users/builder/clone/"
          ./gradlew assemble
          cliclick -m verbose m:12,34
          screencapture -T 1 -x -t png /Users/builder/clone/screen01.png &
          screencapture -T 2 -x -t png /Users/builder/clone/screen02.png &
          screencapture -T 3 -x -t png /Users/builder/clone/screen03.png &
          screencapture -T 10 -x -t png /Users/builder/clone/screen04.png &
          screencapture -T 25 -x -t png /Users/builder/clone/screen05.png &
          screencapture -T 50 -x -t png /Users/builder/clone/screen06.png &
          screencapture -T 60 -x -t png /Users/builder/clone/screen07.png &
          screencapture -T 90 -x -t png /Users/builder/clone/screen09.png &
          screencapture -T 110 -x -t png /Users/builder/clone/screen10.png &
          screencapture -T 200 -x -t png /Users/builder/clone/screenshot-macos.png &
          screencapture -T 230 -x -t png /Users/builder/clone/screen12.png &
          screencapture -T 300 -x -t png /Users/builder/clone/screen13.png &
          pwd
          ls -al
          export AWT_FORCE_HEADFUL=true
          ./gradlew run > trifa.log 2>&1 &
          pwd
          sleep 60
          cliclick -m verbose c:77,124
          sleep 8
          cliclick -m verbose c:139,124
          sleep 2
          cat trifa.log || echo "NO ERR"
          cat /Users/builder/clone/toxid.txt;echo
          cd /Users/builder/clone/java_tox_tester-master/
          /Users/builder/clone/java_tox_tester-master/do_compile.sh
          /Users/builder/clone/java_tox_tester-master/do_run.sh $(cat /Users/builder/clone/toxid.txt) >/dev/null 2>/dev/null &
          sleep 58
          cliclick -m verbose c:195,347
          sleep 90
          sleep 100
          pwd
          ls -al /Users/builder/clone/

    artifacts:
      - /Users/builder/clone/*.png
      - /Users/builder/clone/trifa.log
      - /Users/builder/clone/toxid.txt


