name: "Validate Gradle Wrapper"

on:
  push:
    paths-ignore:
     - 'README.md'
     - 'CHANGELOG.md'
  pull_request:
    paths-ignore:
     - 'README.md'
     - 'CHANGELOG.md'
  workflow_dispatch:
    inputs:
      version:
        description: dummy
        default: dummy

jobs:
  validation:
    name: "Validation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/wrapper-validation-action@v1