name: Nightly

on:
  push:
    paths-ignore:
     - 'README.md'
     - 'CHANGELOG.md'
     - '.github/workflows/nightly.yml'
  pull_request:
    paths-ignore:
     - 'README.md'
     - 'CHANGELOG.md'
     - '.github/workflows/nightly.yml'
  workflow_dispatch:
    inputs:
      version:
        description: dummy
        default: dummy

defaults:
  run:
    shell: bash

jobs:
  update-nightly-tag:
    name: Update nightly release tag
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    permissions:
        contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Move nightly tag to head for nightly release
        run: git tag -f nightly && git push origin nightly -f

  build-linux-nightly-artifact:
    name: Nightly Artifact Linux Build
    runs-on: ubuntu-20.04
    needs: [update-nightly-tag]
    if: |
      always() &&
      (needs.update-nightly-tag.result == 'success' ||
        needs.update-nightly-tag.result == 'skipped')
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: install dependencies
        run: |
          sudo apt-get update && \
          sudo DEBIAN_FRONTEND=noninteractive \
          apt-get install -y --no-install-recommends \
          ca-certificates \
          openjdk-17-jdk \
          openjdk-17-jdk-headless

      - name: show java version
        run:  type -a java;java -version

      - name: set java version
        run:  sudo update-java-alternatives -s java-1.17.0-openjdk-amd64

      - name: show java version
        run:  type -a java;java -version

      - name: build package
        run:  id;pwd;ls -al;./gradlew -Dorg.gradle.java.home=/usr/lib/jvm/java-17-openjdk-amd64 packageDistributionForCurrentOS
      - name: build jar
        run:  id;pwd;ls -al;./gradlew -Dorg.gradle.java.home=/usr/lib/jvm/java-17-openjdk-amd64 packageUberJarForCurrentOS

      - name: check jar
        run:  id;pwd;ls -hal ./build/compose/jars/trifa_material-linux-x64-1.0.0.jar

      - name: check deb
        run:  id;pwd;ls -hal ./build/compose/binaries/main/deb/trifa-material_1.0.0-1_amd64.deb

      - name: Rename artifact for nightly upload
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: |
          cp -v ./build/compose/binaries/main/deb/trifa-material_*_amd64.deb trifa-material_nightly.deb
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: trifa-material_nightly.deb
          path: trifa-material_nightly.deb
      - name: Upload to nightly release
        uses: ncipollo/release-action@v1
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        with:
          allowUpdates: true
          tag: nightly
          omitBodyDuringUpdate: true
          omitNameDuringUpdate: true
          prerelease: true
          replacesArtifacts: true
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "trifa-material_nightly.deb"


  build-macos-nightly-artifact:
    name: Nightly Artifact macOS Build
    runs-on: macos-11
    needs: update-nightly-tag
    if: |
      always() &&
      (needs.update-nightly-tag.result == 'success' ||
        needs.update-nightly-tag.result == 'skipped')
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: install cliclick
        run:  brew install cliclick

      - name: install deps
        run:  brew install git

      - name: test java1
        run:  |
              type java
              java -version || exit 0
              /usr/libexec/java_home -V
              /usr/libexec/java_home -v 17
              export JAVA_HOME=$(/usr/libexec/java_home -v17)
              java -version
              $JAVA_HOME/bin/java -version
              $JAVA_HOME/bin/javac -version
              ls -al /usr/local/Cellar/openjdk/

      - name: build package
        run:  |
          ls -al
          id
          pwd
          export JAVA_HOME=$(/usr/libexec/java_home -v17)
          ./gradlew packageDistributionForCurrentOS

      - name: Rename artifact for nightly upload
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: |
          cp -v /Users/runner/work/trifa_material/trifa_material/build/compose/binaries/main/dmg/trifa_material-*.dmg trifa-material_nightly.dmg
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: trifa-material_nightly.dmg
          path: trifa-material_nightly.dmg
      - name: Upload to nightly release
        uses: ncipollo/release-action@v1
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        with:
          allowUpdates: true
          tag: nightly
          omitBodyDuringUpdate: true
          omitNameDuringUpdate: true
          prerelease: true
          replacesArtifacts: true
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "trifa-material_nightly.dmg"



  build-windows-nightly-artifact:
    name: Nightly Artifact Windows Build
    runs-on: windows-latest
    needs: update-nightly-tag
    if: |
      always() &&
      (needs.update-nightly-tag.result == 'success' ||
        needs.update-nightly-tag.result == 'skipped')
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'

      - name: test java1
        shell: bash
        run:  |
              java -version

      - name: build package
        shell: bash
        run:  |
          ls -al || echo "_"
          id || echo "_"
          pwd || echo "_"
          ./gradlew packageDistributionForCurrentOS

      - name: Rename artifact for nightly upload
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: |
          cp -v ./build/compose/binaries/main/msi/trifa*material*.msi trifa-material_nightly.msi
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: trifa-material_nightly.msi
          path: trifa-material_nightly.msi
      - name: Upload to nightly release
        uses: ncipollo/release-action@v1
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        with:
          allowUpdates: true
          tag: nightly
          omitBodyDuringUpdate: true
          omitNameDuringUpdate: true
          prerelease: true
          replacesArtifacts: true
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "trifa-material_nightly.msi"


